---
2chan.net:
  /b/res/\d+\.htm$:
    image:
      xpath: //form/a/img/../@href

f.hatena.ne.jp:
  /\w+/\d+:
    image:
      xpath: id("foto-body")/img/@src
    title:
      selector: div.fototitle

pixiv.net:
  /member_illust\.php\?mode=big&illust_id=\d+:
    image:
      xpath: //img/@src
  /member_illust\.php\?mode=medium&illust_id=\d+:
    ::follow:
      xpath: id("content2")//a/img/../@href
    'tags[]':
      xpath: id("tags")//a/text()
  ::login:
    form:
      pass: ~
      pixiv_id: ~
    uri: http://www.pixiv.net/

twitpic.com:
  /\w+$:
    ::follow:
      xpath: 'id("photo-controls")/a[@href!="#"]/@href'
    title:
      selector: '#view-photo-caption'
  /\w+/full$:
    image:
      xpath: id("pic")/img/@src

danbooru.donmai.us:
  /post/show/\d+/.+:
    image:
      xpath: id("image")/@src
    'tags[]':
      xpath: id("tag-sidebar")/li/a[2]/text()
